import 'package:audioplayers/audioplayers.dart';
import 'prefs.dart';

/// The app's own short sound effects (bundled in assets/sounds/, generated by
/// tool/gen_sounds.py). Alerts have their own per-channel sounds instead — see
/// NotificationService — so these are only for things that don't notify.
enum UiSound {
  /// Something saved or set: a place, a status, a copied invite.
  tick('cairn_tick.wav'),

  /// Connected with someone after scanning their code.
  connected('cairn_connected.wav');

  final String file;
  const UiSound(this.file);
}

/// Plays [UiSound]s when "Sound effects" is on (the default). They go out on
/// the notification stream without taking audio focus, so they follow the
/// ringer (silent on silent / vibrate) and never pause someone's music.
class SoundService {
  static AudioPlayer? _player;
  static bool? _enabled; // cached; null until first read

  static final _context = AudioContext(
    android: const AudioContextAndroid(
      usageType: AndroidUsageType.notificationEvent,
      contentType: AndroidContentType.sonification,
      audioFocus: AndroidAudioFocus.none,
    ),
    iOS: AudioContextIOS(
      category: AVAudioSessionCategory.ambient, // respects the silent switch
    ),
  );

  static Future<bool> enabled() async =>
      _enabled ??= await Prefs.soundEffects();

  static Future<void> setEnabled(bool v) async {
    _enabled = v;
    await Prefs.setSoundEffects(v);
  }

  /// Play [sound] if sound effects are on. Best-effort: never throws.
  static Future<void> play(UiSound sound) async {
    try {
      if (!await enabled()) return;
    } catch (_) {
      return; // settings unreadable — stay quiet
    }
    await _play(sound.file);
  }

  /// Let someone hear an alert's sound (a copy of its channel sound is bundled
  /// as an asset), whether or not sound effects are on — they asked to.
  static Future<void> previewAlert(String channel) => _play('$channel.wav');

  static Future<void> _play(String file) async {
    try {
      final p = _player ??= AudioPlayer()..setReleaseMode(ReleaseMode.stop);
      await p.stop();
      await p.play(AssetSource('sounds/$file'), ctx: _context);
    } catch (_) {/* no audio output, or unsupported platform */}
  }
}
